version: '3.4'

services:
  finspytgbot:
    image: finspytgbot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
