CREATE TABLE marktes 
(
  name text PRIMARY KEY,
  code text not null,
  yoohooCode text not null,
  location text not null,
  country text not null,
  city text not null,
  delay smallserial not null,
  hour text  not null
);

INSERT INTO
  marktes(
    name,
    code,
    yoohooCode,
    location,
    country,
    city,
    delay,
    hour
  )
VALUES
  ('Euronext Amsterdam Stock Exchange','AS','.AS','Europe','Netherlands','Amsterdam',15,'https://www.tradinghours.com/exchanges/euronext'),
  ('Athens Stock Exchange (ATHEX)','AT','.AT','Europe','Greece','Athens',15,'https://www.tradinghours.com/exchanges/ase-athens'),
  ('Australian Stock Exchange (ASX)','AX','.AX','Australia','Australia','Sydney',20,'https://www.tradinghours.com/exchanges/asx'),
  ('Buenos Aires Stock Exchange (BYMA)','BA','.BA','America','Argentina','Buenos_Aires',30,'https://www.tradinghours.com/exchanges/bcba'),
  ('Budapest Stock Exchange','BD','.BD','Europe','Hungary','Budapest',15,'https://www.tradinghours.com/exchanges/bse-budapest'),
  ('Berlin Stock Exchange','BE','.BE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xber'),
  ('Stock Exchange of Thailand (SET)','BK','.BK','Asia','Thailand','Bangkok',15,'https://www.tradinghours.com/exchanges/set'),
  ('Bombay Stock Exchange','BO','.BO','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/bse-bombay'),
  ('Euronext Brussels','BR','.BR','Europe','Belgium','Brussels',15,'https://www.tradinghours.com/exchanges/euronext-brussels'),
  ('Egyptian Stock Exchange','CA','.CA','Africa','Egypt','Cairo',20,'https://www.tradinghours.com/markets/egx'),
  ('Canadian Securities Exchange','CN','.CN','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/cnsx'),
  ('Nasdaq OMX Copenhagen','CO','.CO','Europe','Denmark','Copenhagen',0,'https://www.tradinghours.com/exchanges/omxc-copenhagen'),
  ('Caracas Stock Exchange','CR','.CR','America','Venezuela','Caracas',15,'https://www.tradinghours.com/exchanges/bvcc'),
  ('Deutsche Boerse XETRA','DE','.DE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xetr'),
  ('Dusseldorf Stock Exchange','DU','.DU','Europe','Germany','Dusseldorf',15,'https://www.tradinghours.com/exchanges/xdus'),
  ('Frankfurt Stock Exchange','F','.F','Europe','Germany','Frankfurt',15,'https://www.tradinghours.com/exchanges/fsx'),
  ('Helsinki Stock Exchange','HE','.HE','Europe','Finland','Helsinki',0,'https://www.tradinghours.com/exchanges/omxh-helsinki'),
  ('Hong Kong Stock Exchange (HKEX)','HK','.HK','Asia','Hong Kong','Hong Kong',15,'https://www.tradinghours.com/exchanges/hkex'),
  ('Hamburg Stock Exchange','HM','.HM','Europe','Germany','Hamburg',15,'https://www.tradinghours.com/exchanges/xham'),
  ('Iceland Stock Exchange','IC','.IC','Atlantic','Iceland','Reykjavik',0,'https://www.tradinghours.com/exchanges/xice'),
  ('Irish Stock Exchange','IR','.IR','Europe','Ireland','Dublin', 15,'https://www.tradinghours.com/exchanges/ise'),
  ('Istanbul Stock Exchange','IS','.IS','Europe','Turkey','Istanbul',15,'https://www.tradinghours.com/exchanges/bist'),
  ('Indonesia Stock Exchange (IDX)','JK','.JK','Asia','Indonesia','Jakarta',10,'https://www.tradinghours.com/exchanges/idx'),
  ('Johannesburg Stock Exchange','JO','.JO','Africa','South Africa','Johannesburg',15,'https://www.tradinghours.com/exchanges/jse'),
  ('Malaysian Stock Exchange','KL','.KL','Asia','Malaysia','Kuala_Lumpur',15,'https://www.tradinghours.com/exchanges/myx'),
  ('Korea Exchange (KOSDAQ)','KQ','.KQ','Asia','South Korea','Seoul',20,'https://www.tradinghours.com/exchanges/kosdaq'),
  ('South Korea Stock Exchange','KS','.KS','Asia','South Korea','Seoul',20,'https://www.tradinghours.com/exchanges/krx'),
  ('London Stock Exchange','L','.L','Europe','United Kingdom','London',20,'https://www.tradinghours.com/exchanges/lse'),
  ('Euronext Lisbon','LS','.LS','Europe','Portugal','Lisbon',15,'https://www.tradinghours.com/exchanges/euronext-lisbon'),
  ('Madrid Stock Exchange','MC','.MC','Europe','Spain','Madrid',15,'https://www.tradinghours.com/exchanges/bme'),
  ('Moscow Exchange (MOEX)','ME','.ME','Europe','Russia','Moscow',15,'https://www.tradinghours.com/exchanges/moex'),
  ('Italian Stock Exchange','MI','.MI','Europe','Italy','Rome',20,'https://www.tradinghours.com/exchanges/mta'),
  ('Munich Stock Exchange','MU','.MU','Europe','Germany','Munich', 15,'https://www.tradinghours.com/exchanges/xmun'),
  ('Mexico Stock Exchange (BMV)','MX','.MX','America','Mexico','Mexico_City',20,'https://www.tradinghours.com/exchanges/bmv'),
  ('NEO Exchange','NE','.NE','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/neo'),
  ('National Stock Exchange of India','NS','.NS','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/nse-india'),
  ('New Zealand Stock Exchange (NZX)','NZ','.NZ','Pacific','New Zealand','Wellington',20,'https://www.tradinghours.com/exchanges/nzx'),
  ('Oslo Stock Exchange','OL','.OL','Europe','Norway','Oslo',15,'https://www.tradinghours.com/exchanges/ose'),
  ('Euronext Paris Exchange','PA','.PA','Europe','France','Paris',15,'https://www.tradinghours.com/exchanges/euronext-paris'),
  ('Prague Stock Exchange','PR','.PR','Europe','Czech Republic','Prague',20,'https://www.tradinghours.com/exchanges/xpra'),
  ('Qatar Stock Exchange','QA','.QA','Asia','Qatar','Doha',15,'https://www.tradinghours.com/exchanges/qe'),
  ('Riga Stock Exchange','RG','.RG','Europe','Latvia','Riga',0,'https://www.tradinghours.com/exchanges/omxr-riga'),
  ('Brazil Stock Exchange','SA','.SA','America','Brazil','Sao_Paulo',15,'https://www.tradinghours.com/exchanges/bovespa'),
  ('Stuttgart Stock Exchange','SG','.SG','Europe','Germany','Stuttgart',15,'https://www.tradinghours.com/exchanges/xstu'),
  ('Singapore Stock Exchange (SGX)','SI','.SI','Asia','Singapore','Singapore',20,'https://www.tradinghours.com/exchanges/sgx'),
  ('Santiago Stock Exchange','SN','.SN','America','Chile','Santiago',15,'https://www.tradinghours.com/exchanges/bvs'),
  ('Saudi Stock Exchange (Tadawul)','SR','.SAU','Asia','Saudi Arabia','Riyadh',15,'https://www.tradinghours.com/exchanges/tadawul'),
  ('Shanghai Stock Exchange','SS','.SS','Asia','China','Shanghai',30,'https://www.tradinghours.com/exchanges/sse'),
  ('Nordic Growth Market','ST','.ST','Europe','Sweden','Stockholm',0,'https://www.tradinghours.com/exchanges/xngm'),
  ('Swiss Exchange (SIX)','SW','.SW','Europe','Switzerland','Zurich',30,'https://www.tradinghours.com/exchanges/six'),
  ('Shenzhen Stock Exchange','SZ','.SZ','Asia','China','Shenzhen',30,'https://www.tradinghours.com/exchanges/szse'),
  ('Tokyo Stock Exchange','T','.T','Asia','Japan','Tokyo',20,'https://www.tradinghours.com/exchanges/jpx'),
  ('Tel Aviv Stock Exchange','TA','.TA','Asia','Israel','Tel Aviv',20,'https://www.tradinghours.com/exchanges/tase'),
  ('Tallinn Stock Exchange','TL','.TL','Europe','Estonia','Tallinn',0,'https://www.tradinghours.com/exchanges/omxt-tallinn'),
  ('Toronto Stock Exchange (TSX)','TO','.TO','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/tsx'),
  ('Taiwan Stock Exchange (TWSE)','TW','.TW','Asia','Taiwan','Taipei',20,'https://www.tradinghours.com/exchanges/twse'),
  ('New York Stock Exchange','US','-','America','United States of America','New York',0,'https://www.tradinghours.com/markets/nyse'),
  ('Nasdaq Stock Exchange','US','-','America','United States of America','New York',0,'https://www.tradinghours.com/markets/nasdaq'),
  ('TSX Venture Exchange (TSXV)','V','.V','America','Canada','Calgary',0,'https://www.tradinghours.com/exchanges/xtsx'),
  ('Vienna Stock Exchange','VI','.VI','Europe','Austria','Vienna',15,'https://www.tradinghours.com/exchanges/vse'),
  ('Nasdaq Vilnius Stock Exchange','VS','.VS','Europe','Lithuania','Vilnius',0,'https://www.tradinghours.com/exchanges/omxv-vilnius'),
  ('Hanover Stock Exchange','HA','.HA','Europe','Germany','Hanover',15,'https://www.tradinghours.com/markets/xhan');