CREATE TABLE marktes 
(
  name text, 
  code text not null,
  mic text PRIMARY KEY,
  yahoo_code text not null,
  location text not null,
  country text not null,
  city text not null,
  delay smallserial not null,
  hour text  not null
);

INSERT INTO
  markets(
    name,
    code,
    mic,
    yahoo_code,
    location,
    country,
    city,
    delay,
    hour
  )
VALUES
  ('Euronext Amsterdam Stock Exchange','AS','XAMS','.AS','Europe','Netherlands','Amsterdam',15,'https://www.tradinghours.com/exchanges/euronext'),
  ('Athens Stock Exchange (ATHEX)','AT','ASEX','.AT','Europe','Greece','Athens',15,'https://www.tradinghours.com/exchanges/ase-athens'),
  ('Australian Stock Exchange (ASX)','AX','XASX','.AX','Australia','Australia','Sydney',20,'https://www.tradinghours.com/exchanges/asx'),
  ('Buenos Aires Stock Exchange (BYMA)','BA','XBUE','.BA','America','Argentina','Buenos_Aires',30,'https://www.tradinghours.com/exchanges/bcba'),
  ('Budapest Stock Exchange','BD','XBUD','.BD','Europe','Hungary','Budapest',15,'https://www.tradinghours.com/exchanges/bse-budapest'),
  ('Berlin Stock Exchange','BE','XBER','.BE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xber'),
  ('Stock Exchange of Thailand (SET)','BK','XBKK','.BK','Asia','Thailand','Bangkok',15,'https://www.tradinghours.com/exchanges/set'),
  ('Bombay Stock Exchange','BO','XBOM','.BO','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/bse-bombay'),
  ('Euronext Brussels','BR','XBRU','.BR','Europe','Belgium','Brussels',15,'https://www.tradinghours.com/exchanges/euronext-brussels'),
  ('Egyptian Stock Exchange','CA','XCAI','.CA','Africa','Egypt','Cairo',20,'https://www.tradinghours.com/markets/egx'),
  ('Canadian Securities Exchange','CN','XCNQ','.CN','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/cnsx'),
  ('Nasdaq OMX Copenhagen','CO','XCSE','.CO','Europe','Denmark','Copenhagen',0,'https://www.tradinghours.com/exchanges/omxc-copenhagen'),
  ('Caracas Stock Exchange','CR','BVCA','.CR','America','Venezuela','Caracas',15,'https://www.tradinghours.com/exchanges/bvcc'),
  ('Deutsche Boerse XETRA','DE','XETR','.DE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xetr'),
  ('Dusseldorf Stock Exchange','DU','XDUS','.DU','Europe','Germany','Dusseldorf',15,'https://www.tradinghours.com/exchanges/xdus'),
  ('Frankfurt Stock Exchange','F','XFRA','.F','Europe','Germany','Frankfurt',15,'https://www.tradinghours.com/exchanges/fsx'),
  ('Helsinki Stock Exchange','HE','XHEL','.HE','Europe','Finland','Helsinki',0,'https://www.tradinghours.com/exchanges/omxh-helsinki'),
  ('Hong Kong Stock Exchange (HKEX)','HK','XHKG','.HK','Asia','Hong Kong','Hong Kong',15,'https://www.tradinghours.com/exchanges/hkex'),
  ('Hamburg Stock Exchange','HM','XHAM','.HM','Europe','Germany','Hamburg',15,'https://www.tradinghours.com/exchanges/xham'),
  ('Iceland Stock Exchange','IC','XICE','.IC','Atlantic','Iceland','Reykjavik',0,'https://www.tradinghours.com/exchanges/xice'),
  ('Irish Stock Exchange','IR','XDUB','.IR','Europe','Ireland','Dublin', 15,'https://www.tradinghours.com/exchanges/ise'),
  ('Istanbul Stock Exchange','IS','XIST','.IS','Europe','Turkey','Istanbul',15,'https://www.tradinghours.com/exchanges/bist'),
  ('Indonesia Stock Exchange (IDX)','JK','XIDX','.JK','Asia','Indonesia','Jakarta',10,'https://www.tradinghours.com/exchanges/idx'),
  ('Johannesburg Stock Exchange','JO','XJSE','.JO','Africa','South Africa','Johannesburg',15,'https://www.tradinghours.com/exchanges/jse'),
  ('Malaysian Stock Exchange','KL','XKLS','.KL','Asia','Malaysia','Kuala_Lumpur',15,'https://www.tradinghours.com/exchanges/myx'),
  ('Korea Exchange (KOSDAQ)','KQ','XKOS','.KQ','Asia','South Korea','Seoul',20,'https://www.tradinghours.com/exchanges/kosdaq'),
  ('South Korea Stock Exchange','KS','XKRX','.KS','Asia','South Korea','Seoul',20,'https://www.tradinghours.com/exchanges/krx'),
  ('London Stock Exchange','L','XLON','.L','Europe','United Kingdom','London',20,'https://www.tradinghours.com/exchanges/lse'),
  ('Euronext Lisbon','LS','XLIS','.LS','Europe','Portugal','Lisbon',15,'https://www.tradinghours.com/exchanges/euronext-lisbon'),
  ('Madrid Stock Exchange','MC','XMAD','.MC','Europe','Spain','Madrid',15,'https://www.tradinghours.com/exchanges/bme'),
  ('Moscow Exchange (MOEX)','ME','MISX','.ME','Europe','Russia','Moscow',15,'https://www.tradinghours.com/exchanges/moex'),
  ('Italian Stock Exchange','MI','XMIL','.MI','Europe','Italy','Rome',20,'https://www.tradinghours.com/exchanges/mta'),
  ('Munich Stock Exchange','MU','XMUN','.MU','Europe','Germany','Munich', 15,'https://www.tradinghours.com/exchanges/xmun'),
  ('Mexico Stock Exchange (BMV)','MX','XMEX','.MX','America','Mexico','Mexico_City',20,'https://www.tradinghours.com/exchanges/bmv'),
  ('NEO Exchange','NE','NEOE','.NE','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/neo'),
  ('National Stock Exchange of India','NS','XNSE','.NS','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/nse-india'),
  ('New Zealand Stock Exchange (NZX)','NZ','XNZE','.NZ','Pacific','New Zealand','Wellington',20,'https://www.tradinghours.com/exchanges/nzx'),
  ('Oslo Stock Exchange','OL','XOSL','.OL','Europe','Norway','Oslo',15,'https://www.tradinghours.com/exchanges/ose'),
  ('Euronext Paris Exchange','PA','XPAR','.PA','Europe','France','Paris',15,'https://www.tradinghours.com/exchanges/euronext-paris'),
  ('Prague Stock Exchange','PR','XPRA','.PR','Europe','Czech Republic','Prague',20,'https://www.tradinghours.com/exchanges/xpra'),
  ('Qatar Stock Exchange','QA','DSMD','.QA','Asia','Qatar','Doha',15,'https://www.tradinghours.com/exchanges/qe'),
  ('Riga Stock Exchange','RG','XRIS','.RG','Europe','Latvia','Riga',0,'https://www.tradinghours.com/exchanges/omxr-riga'),
  ('Brazil Stock Exchange','SA','BVMF','.SA','America','Brazil','Sao_Paulo',15,'https://www.tradinghours.com/exchanges/bovespa'),
  ('Stuttgart Stock Exchange','SG','XSTU','.SG','Europe','Germany','Stuttgart',15,'https://www.tradinghours.com/exchanges/xstu'),
  ('Singapore Stock Exchange (SGX)','SI','XSES','.SI','Asia','Singapore','Singapore',20,'https://www.tradinghours.com/exchanges/sgx'),
  ('Santiago Stock Exchange','SN','XSGO','.SN','America','Chile','Santiago',15,'https://www.tradinghours.com/exchanges/bvs'),
  ('Saudi Stock Exchange (Tadawul)','SR','XSAU','.SAU','Asia','Saudi Arabia','Riyadh',15,'https://www.tradinghours.com/exchanges/tadawul'),
  ('Shanghai Stock Exchange','SS','XSHG','.SS','Asia','China','Shanghai',30,'https://www.tradinghours.com/exchanges/sse'),
  ('Nordic Growth Market','ST','XNGM','.ST','Europe','Sweden','Stockholm',0,'https://www.tradinghours.com/exchanges/xngm'),
  ('Swiss Exchange (SIX)','SW','XSWX','.SW','Europe','Switzerland','Zurich',30,'https://www.tradinghours.com/exchanges/six'),
  ('Shenzhen Stock Exchange','SZ','XSHE','.SZ','Asia','China','Shenzhen',30,'https://www.tradinghours.com/exchanges/szse'),
  ('Tokyo Stock Exchange','T','XJPX','.T','Asia','Japan','Tokyo',20,'https://www.tradinghours.com/exchanges/jpx'),
  ('Tel Aviv Stock Exchange','TA','XTAE','.TA','Asia','Israel','Tel Aviv',20,'https://www.tradinghours.com/exchanges/tase'),
  ('Tallinn Stock Exchange','TL','XTAL','.TL','Europe','Estonia','Tallinn',0,'https://www.tradinghours.com/exchanges/omxt-tallinn'),
  ('Toronto Stock Exchange (TSX)','TO','XTSE','.TO','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/tsx'),
  ('Taiwan Stock Exchange (TWSE)','TW','XTAI','.TW','Asia','Taiwan','Taipei',20,'https://www.tradinghours.com/exchanges/twse'),
  ('TSX Venture Exchange (TSXV)','V','XTSX','.V','America','Canada','Calgary',0,'https://www.tradinghours.com/exchanges/xtsx'),
  ('Vienna Stock Exchange','VI', 'XWBO','.VI','Europe','Austria','Vienna',15,'https://www.tradinghours.com/exchanges/vse'),
  ('Nasdaq Vilnius Stock Exchange','VS','XLIT','.VS','Europe','Lithuania','Vilnius',0,'https://www.tradinghours.com/exchanges/omxv-vilnius'),
  ('Hanover Stock Exchange','HA','XHAN','.HA','Europe','Germany','Hanover',15,'https://www.tradinghours.com/markets/xhan'),
  ('New York Stock Exchange','US','XNYS','-','America','United States of America','New York',0,'https://www.tradinghours.com/markets/nyse'),
  ('Nasdaq Stock Exchange','US','XNAS','-','America','United States of America','New York',0,'https://www.tradinghours.com/markets/nasdaq');