CREATE TABLE marktes 
(
  name text, 
  code text not null,
  mic text PRIMARY KEY,
  yahoo_code text not null,
  location text not null,
  country text not null,
  city text not null,
  delay smallserial not null,
  hour text  not null
);

INSERT INTO
  markets(
    name,
    code,
    mic,
    yahoo_code,
    location,
    country,
    city,
    delay,
    hour
  )
VALUES
  ('Euronext_Amsterdam_Stock_Exchange','AS','XAMS','.AS','Europe','Netherlands','Amsterdam',15,'https://www.tradinghours.com/exchanges/euronext'),
  ('Athens_Stock_Exchange','AT','ASEX','.AT','Europe','Greece','Athens',15,'https://www.tradinghours.com/exchanges/ase-athens'),
  ('Australian_Stock_Exchange','AX','XASX','.AX','Australia','Australia','Sydney',20,'https://www.tradinghours.com/exchanges/asx'),
  ('Buenos_Aires_Stock_Exchange','BA','XBUE','.BA','America','Argentina','Buenos_Aires',30,'https://www.tradinghours.com/exchanges/bcba'),
  ('Budapest_Stock_Exchange','BD','XBUD','.BD','Europe','Hungary','Budapest',15,'https://www.tradinghours.com/exchanges/bse-budapest'),
  ('Berlin_Stock_Exchange','BE','XBER','.BE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xber'),
  ('Stock_Exchange_of_Thailand','BK','XBKK','.BK','Asia','Thailand','Bangkok',15,'https://www.tradinghours.com/exchanges/set'),
  ('Bombay_Stock_Exchange','BO','XBOM','.BO','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/bse-bombay'),
  ('Euronext_Brussels','BR','XBRU','.BR','Europe','Belgium','Brussels',15,'https://www.tradinghours.com/exchanges/euronext-brussels'),
  ('Egyptian_Stock_Exchange','CA','XCAI','.CA','Africa','Egypt','Cairo',20,'https://www.tradinghours.com/markets/egx'),
  ('Canadian_Securities_Exchange','CN','XCNQ','.CN','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/cnsx'),
  ('Nasdaq_OMX_Copenhagen','CO','XCSE','.CO','Europe','Denmark','Copenhagen',0,'https://www.tradinghours.com/exchanges/omxc-copenhagen'),
  ('Caracas_Stock_Exchange','CR','BVCA','.CR','America','Venezuela','Caracas',15,'https://www.tradinghours.com/exchanges/bvcc'),
  ('Deutsche_Boerse_XETRA','DE','XETR','.DE','Europe','Germany','Berlin',15,'https://www.tradinghours.com/exchanges/xetr'),
  ('Dusseldorf_Stock_Exchange','DU','XDUS','.DU','Europe','Germany','Dusseldorf',15,'https://www.tradinghours.com/exchanges/xdus'),
  ('Frankfurt_Stock_Exchange','F','XFRA','.F','Europe','Germany','Frankfurt',15,'https://www.tradinghours.com/exchanges/fsx'),
  ('Helsinki_Stock_Exchange','HE','XHEL','.HE','Europe','Finland','Helsinki',0,'https://www.tradinghours.com/exchanges/omxh-helsinki'),
  ('Hong_Kong_Stock_Exchange','HK','XHKG','.HK','Asia','Hong_Kong','Hong_Kong',15,'https://www.tradinghours.com/exchanges/hkex'),
  ('Hamburg_Stock_Exchange','HM','XHAM','.HM','Europe','Germany','Hamburg',15,'https://www.tradinghours.com/exchanges/xham'),
  ('Iceland_Stock_Exchange','IC','XICE','.IC','Atlantic','Iceland','Reykjavik',0,'https://www.tradinghours.com/exchanges/xice'),
  ('Irish_Stock_Exchange','IR','XDUB','.IR','Europe','Ireland','Dublin', 15,'https://www.tradinghours.com/exchanges/ise'),
  ('Istanbul_Stock_Exchange','IS','XIST','.IS','Europe','Turkey','Istanbul',15,'https://www.tradinghours.com/exchanges/bist'),
  ('Indonesia_Stock_Exchange','JK','XIDX','.JK','Asia','Indonesia','Jakarta',10,'https://www.tradinghours.com/exchanges/idx'),
  ('Johannesburg_Stock_Exchange','JO','XJSE','.JO','Africa','South_Africa','Johannesburg',15,'https://www.tradinghours.com/exchanges/jse'),
  ('Malaysian_Stock_Exchange','KL','XKLS','.KL','Asia','Malaysia','Kuala_Lumpur',15,'https://www.tradinghours.com/exchanges/myx'),
  ('Korea_Exchange','KQ','XKOS','.KQ','Asia','South_Korea','Seoul',20,'https://www.tradinghours.com/exchanges/kosdaq'),
  ('South_Korea_Stock_Exchange','KS','XKRX','.KS','Asia','South_Korea','Seoul',20,'https://www.tradinghours.com/exchanges/krx'),
  ('London_Stock_Exchange','L','XLON','.L','Europe','United_Kingdom','London',20,'https://www.tradinghours.com/exchanges/lse'),
  ('Euronext_Lisbon','LS','XLIS','.LS','Europe','Portugal','Lisbon',15,'https://www.tradinghours.com/exchanges/euronext-lisbon'),
  ('Madrid_Stock_Exchange','MC','XMAD','.MC','Europe','Spain','Madrid',15,'https://www.tradinghours.com/exchanges/bme'),
  ('Moscow_Exchange','ME','MISX','.ME','Europe','Russia','Moscow',15,'https://www.tradinghours.com/exchanges/moex'),
  ('Italian_Stock_Exchange','MI','XMIL','.MI','Europe','Italy','Rome',20,'https://www.tradinghours.com/exchanges/mta'),
  ('Munich_Stock_Exchange','MU','XMUN','.MU','Europe','Germany','Munich', 15,'https://www.tradinghours.com/exchanges/xmun'),
  ('Mexico_Stock_Exchange','MX','XMEX','.MX','America','Mexico','Mexico_City',20,'https://www.tradinghours.com/exchanges/bmv'),
  ('NEO_Exchange','NE','NEOE','.NE','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/neo'),
  ('National_Stock_Exchange_of_India','NS','XNSE','.NS','Asia','India','Mumbai',0,'https://www.tradinghours.com/exchanges/nse-india'),
  ('New_Zealand_Stock_Exchange','NZ','XNZE','.NZ','Pacific','New_Zealand','Wellington',20,'https://www.tradinghours.com/exchanges/nzx'),
  ('Oslo_Stock_Exchange','OL','XOSL','.OL','Europe','Norway','Oslo',15,'https://www.tradinghours.com/exchanges/ose'),
  ('Euronext_Paris_Exchange','PA','XPAR','.PA','Europe','France','Paris',15,'https://www.tradinghours.com/exchanges/euronext-paris'),
  ('Prague_Stock_Exchange','PR','XPRA','.PR','Europe','Czech_Republic','Prague',20,'https://www.tradinghours.com/exchanges/xpra'),
  ('Qatar_Stock_Exchange','QA','DSMD','.QA','Asia','Qatar','Doha',15,'https://www.tradinghours.com/exchanges/qe'),
  ('Riga_Stock_Exchange','RG','XRIS','.RG','Europe','Latvia','Riga',0,'https://www.tradinghours.com/exchanges/omxr-riga'),
  ('Brazil_Stock_Exchange','SA','BVMF','.SA','America','Brazil','Sao_Paulo',15,'https://www.tradinghours.com/exchanges/bovespa'),
  ('Stuttgart_Stock_Exchange','SG','XSTU','.SG','Europe','Germany','Stuttgart',15,'https://www.tradinghours.com/exchanges/xstu'),
  ('Singapore_Stock_Exchange','SI','XSES','.SI','Asia','Singapore','Singapore',20,'https://www.tradinghours.com/exchanges/sgx'),
  ('Santiago_Stock_Exchange','SN','XSGO','.SN','America','Chile','Santiago',15,'https://www.tradinghours.com/exchanges/bvs'),
  ('Saudi_Stock_Exchange','SR','XSAU','.SAU','Asia','Saudi_Arabia','Riyadh',15,'https://www.tradinghours.com/exchanges/tadawul'),
  ('Shanghai_Stock_Exchange','SS','XSHG','.SS','Asia','China','Shanghai',30,'https://www.tradinghours.com/exchanges/sse'),
  ('Nordic_Growth_Market','ST','XNGM','.ST','Europe','Sweden','Stockholm',0,'https://www.tradinghours.com/exchanges/xngm'),
  ('Swiss_Exchange','SW','XSWX','.SW','Europe','Switzerland','Zurich',30,'https://www.tradinghours.com/exchanges/six'),
  ('Shenzhen_Stock_Exchange','SZ','XSHE','.SZ','Asia','China','Shenzhen',30,'https://www.tradinghours.com/exchanges/szse'),
  ('Tokyo_Stock_Exchange','T','XJPX','.T','Asia','Japan','Tokyo',20,'https://www.tradinghours.com/exchanges/jpx'),
  ('Tel_Aviv_Stock_Exchange','TA','XTAE','.TA','Asia','Israel','Tel_Aviv',20,'https://www.tradinghours.com/exchanges/tase'),
  ('Tallinn_Stock_Exchange','TL','XTAL','.TL','Europe','Estonia','Tallinn',0,'https://www.tradinghours.com/exchanges/omxt-tallinn'),
  ('Toronto_Stock_Exchange','TO','XTSE','.TO','America','Canada','Toronto',0,'https://www.tradinghours.com/exchanges/tsx'),
  ('Taiwan_Stock_Exchange','TW','XTAI','.TW','Asia','Taiwan','Taipei',20,'https://www.tradinghours.com/exchanges/twse'),
  ('TSX_Venture_Exchange','V','XTSX','.V','America','Canada','Calgary',0,'https://www.tradinghours.com/exchanges/xtsx'),
  ('Vienna_Stock_Exchange','VI', 'XWBO','.VI','Europe','Austria','Vienna',15,'https://www.tradinghours.com/exchanges/vse'),
  ('Nasdaq_Vilnius_Stock_Exchange','VS','XLIT','.VS','Europe','Lithuania','Vilnius',0,'https://www.tradinghours.com/exchanges/omxv-vilnius'),
  ('Hanover_Stock_Exchange','HA','XHAN','.HA','Europe','Germany','Hanover',15,'https://www.tradinghours.com/markets/xhan'),
  ('New_York_Stock_Exchange','US','XNYS','-','America','United_States_of_America','New York',0,'https://www.tradinghours.com/markets/nyse'),
  ('Nasdaq_Stock_Exchange','US','XNAS','-','America','United_States_of_America','New York',0,'https://www.tradinghours.com/markets/nasdaq');